/**
 * Exception during resolution should be wrapped and re-thrown.
 */
@Test
public void testSetValue08() {
    doThrowableTest(TesterBeanNameResolver.EXCEPTION_TRIGGER_NAME, MethodUnderTest.SET_VALUE);
}